### PR TITLE
acpi-tables: switch to using libgpiod when DISTRO_FEATURES has acpi

### PR DESCRIPTION
**Pull request by htot**
Signed-off-by: Ferry Toth <ftoth@exalondelft.nl>

### CODE REVIEW

**Comment by htot** [comment]
When acpi is enabled pinmux's are controlled by loading acpi tables. However, Edison Arduino requires TRI_STATE_ALL be toggled, which is normally handled by MRAA. Echoing to the pin number doesn't seem to work reliably, so change to gpiolib. This code is incorporated into initramfs, so acpi tables are loaded and TRI_STATE_ALL toggled as early as possible without loading acpi.cpio to memory from U-Boot.

This can be tested by enabling acpi or building pyro64_acpi and testing i2c. Without this patch the following will not work:
```
modprobe -i i2c-dev                                                                                                                                                                    
i2cdetect -r 1
#WARNING! This program can confuse your I2C bus, cause data loss and worse!
I will probe file /dev/i2c-1 using read byte commands.
I will probe address range 0x03-0x77.
Continue? [Y/n] 
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:          -- -- -- -- -- -- -- -- -- -- -- -- -- 
10: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
20: UU UU UU UU -- -- -- -- -- -- -- -- -- -- -- -- 
30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
60: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
70: -- -- -- -- -- -- -- --
```

**Review by alext-mkrs — APPROVED** [review]
LGTM

**Comment by alext-mkrs** [comment]
...by inspection, that is - if you want me to build-test, let me know, I'm currently a bit distracted to do that by default - I'm setting up a real host for Yocto builds, for whatever reason VirtualBox has become noticeably slow (either in 5.2.x or those recent OS updates) and finally motivated me to bite the bullet.

**Comment by htot** [comment]
Inspection is good enough. This code has only effect with acpi enabled and works (the code in the repo doesn't).

I'm on Kubuntu 18.04 BTW, despite the build warning this works fine.

**Comment by htot** [comment]
Thanks, merged.

**Pull request merged**
